### ISSUE TITLE
Roll All and Roll NPCs

### ISSUE THREAD

**Issue by Helm70** [vtt-lair/foundry-group-initiative#17]
I've noticed recently that the "roll all" and "roll npcs" button seems to be non-functional. It works for the first attempt but locks up afterwards. Rolling individual initiatives seems to be ok.

I'm running Foundry 0.8.9 and D&D 5e 1.5.5

**Comment by Aymeeeric** [comment]
Yes, same thing here... The module does not work anymore on "roll all" and "roll npcs" (Foundry 0.8.9 and D&D 5e 1.5.5).

**Comment by vtt-lair** [comment]
@Helm70 and @Aymeeeric can you possibly give me more details? 

I've tried using both buttons on a first attempt and subsequent attempts without issue:

- I've added all combatants to the tracker, click Roll NPC and Roll All and it rolls
- Then I would add new combatants (from the same actor) and the initiative is automatically updated to the previously rolled ones.

- I've added all combatants to the tracker, click Roll NPC and Roll All and it rolls. 
- Then added new combatants from a different actor to the tracker and was able to roll for them using the buttons too

- I've added all combatants to the tracker, click Roll NPC and Roll All and it rolls. 
- Then reset the encounter and was able to roll using both buttons.

The only time where it doesn't roll is if ALL the combatants already have an initiative, however this is standard core functionality of Foundry, that you can't roll if all the combatants already have initiative.

**Comment by KasaiSV** [comment]
I'm having the same exact issue. 

The first encounter that I begin after launching/refreshing FVTT works fine and the initiative buttons function without issue. Once I have ended that encounter, if I try to start another one, either on the same scene or a different scene, the two buttons are completely non-functional. Additionally, the error doesn't require initiative to be rolled in the first encounter. If I create an encounter, immediately delete it, and then create a second one, it will not function.

This only happens when the "Roll group initiative" option is selected in the Combat Tracker Settings. Additionally, while I'm in the first encounter (the functioning one) I can add additional tokens to the encounter, both prior to and after hitting the "Begin Combat" button at the bottom of the tracker, and the buttons continue to work. I can also hit the "Reset Initiative" button and am able to use the buttons successfully without issue, as long as it is the same encounter. Once the encounter ends and I begin a new one, none of this works.

I'm hoping this might help shed some light on things: In some cases, instead of the buttons doing nothing, they disappear after being clicked on and I am given an error that reads as follows 
![unknown](https://user-images.githubusercontent.com/73495745/146667034-ec470ad8-8d10-4de6-abf3-2630e9e9edd9.png)
: 

Here is a picture showing the buttons being gone:
![image](https://user-images.githubusercontent.com/73495745/146667137-adaeaae5-7ff5-4ffe-82ad-0aab6c93d6b9.png)

Once I get the error, until restarting FVTT I will continue getting the error (along with the disappearing buttons) whenever I make a new encounter and try to use the "Roll All" or "Roll NPC" buttons. The combat ID listed in the error is the same each time, until I restart FVTT, but the next time I run across the error, the ID will be different.

So to quickly summarize the steps I take to reproduce the problem:

1. Open FVTT and create a new combat encounter (insuring that the group initiative option is selected).
2. End the combat encounter. This can be done either by clicking the trashcan icon, or by clicking the "begin combat" button followed by the "end combat" button. It does not matter if the "Roll All" or "Roll NPC" buttons were used during this encounter.
3. Create a new combat encounter.
4. Attempt to click the "Roll All" or "Roll NPC" buttons.
5. The buttons will either do absolutely nothing with no feedback, or they will disappear from the combat tracker and will spit out the error I attached above. I do not know what determines whether they simply don't work/spit the error.

**Comment by Helm70** [comment]
I started Foundry VTT without any modules enabled and again, group initiative works ok the first time I "roll all" or "roll npcs" but for the 2nd encounter, the buttons become unresponsive.

**Comment by vtt-lair** [comment]
Thanks for the details. Will see what is going on here... from the error shared it almost looks like it's not ending the combat for some reason, even though it's ended,

**Comment by vtt-lair** [comment]
For interest sake, @KasaiSV, @Helm70 do you guys have lipWrapper installed?

**Comment by KasaiSV** [comment]
I do and have had it enabled when testing.

**Comment by Aymeeeric** [comment]
> I'm having the same exact issue. Everything I've tested below has been with only the Group Initiative module (and any dependency modules) active, and nothing else. Also, for what it's worth, I had a game back on 11/19/2021 during which I can safely say the issue was not happening.
> 
> The first encounter that I begin after launching/refreshing FVTT works fine and the initiative buttons function without issue. Once I have ended that encounter, if I try to start another one, either on the same scene or a different scene, the two buttons are completely non-functional. Additionally, the error doesn't require initiative to be rolled in the first encounter. If I create an encounter, immediately delete it, and then create a second one, it will not function.
> 
> This only happens when the "Roll group initiative" option is selected in the Combat Tracker Settings. Additionally, while I'm in the first encounter (the functioning one) I can add additional tokens to the encounter, both prior to and after hitting the "Begin Combat" button at the bottom of the tracker, and the buttons continue to work. I can also hit the "Reset Initiative" button and am able to use the buttons successfully without issue, as long as it is the same encounter. Once the encounter ends and I begin a new one, none of this works.
> 
> I'm hoping this might help shed some light on things: In some cases, instead of the buttons doing nothing, they disappear after being clicked on and I am given an error that reads as follows: ![unknown](https://user-images.githubusercontent.com/73495745/146667034-ec470ad8-8d10-4de6-abf3-2630e9e9edd9.png)
> 
> Here is a picture showing the buttons being gone: ![image](https://user-images.githubusercontent.com/73495745/146667137-adaeaae5-7ff5-4ffe-82ad-0aab6c93d6b9.png)
> 
> Once I get the error popup, until restarting FVTT I will continue getting the error (along with the disappearing buttons) whenever I make a new encounter and try to use the "Roll All" or "Roll NPC" buttons. The combat ID listed in the error is the same each time, until I restart FVTT, but the next time I run across the error, the ID will be different.
> 
> So to quickly summarize the steps I take to reproduce the problem:
> 
> 1. Open FVTT and create a new combat encounter (insuring that the group initiative option is selected).
> 2. End the combat encounter. This can be done either by clicking the trashcan icon, or by clicking the "begin combat" button followed by the "end combat" button. It does not matter if the "Roll All" or "Roll NPC" buttons were used during this encounter.
> 3. Create a new combat encounter.
> 4. Attempt to click the "Roll All" or "Roll NPC" buttons.
> 5. The buttons will either do absolutely nothing with no feedback, or they will disappear from the combat tracker and will spit out the error I attached above. I do not know what determines whether they simply don't work/spit the error.

This is exactly what is happening to me.
@vtt-lair : lipWrapper installed here :)

**Comment by vtt-lair** [comment]
@KasaiSV thanks for the detailed report. I was able to replicate your issue... now to try and figure out what is going wrong

**Comment by vtt-lair** [comment]
@KasaiSV , @Aymeeeric , @Helm70 I found the issue! I registered taking over the Roll NPC and Roll All functionality with my functions with libWrapper, but never unregistered the functions when deleting combat. 

As such, when creating a new encounter. The functions were linked to the old combat data and when clicking Roll NPC or Roll All, it saw that there was already initiatives and just noped out.

I've fixed it, just want to run through a few test still and have a family thing on in an hour. So will try and release this fix tonight (for me) still.

Thanks again... the detailed report really helped me figure out the issue!

**Comment by Helm70** [comment]
I really appreciate your quick response into resolving this.

**Comment by vtt-lair** [comment]
Just released the new version, please let me know if it's behaving like a good module now

**Comment by Helm70** [comment]
Working fine now. Much appreciated!

**Comment by Aymeeeric** [comment]
Same here! Thanks a lot @vtt-lair.
