### ISSUE TITLE
Modification of Core HTML Tag - "Details" breaks core FoundryVTT Functions

### ISSUE THREAD

**Issue by Aeristoka** [vtt-lair/foundry-group-initiative#25]
https://github.com/vtt-lair/foundry-group-initiative/blob/master/templates/group-collapse.html

The CSS in that template which modifies the Details core HTML Tag breaks the placement of arrows in many places that they are used in FoundryVTT.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

In example, a chat message posted with a Details element working properly:

![image](https://user-images.githubusercontent.com/7988297/148656055-9a319795-5bc9-47f0-8e2c-26c871fdac76.png)

And the exact same Chat Message with this module enabled:

![image](https://user-images.githubusercontent.com/7988297/148656069-0202b3d7-c9e7-4f76-93cb-75c2ccb9a9d1.png)

**Comment by kakaroto** [comment]
Note: The message using the `details` tag posted above is from Beyond20. customizing CSS of core html tags is problematic because of conflicts like these. Your own html should be using a class and your CSS should be specific to that class, for example : 
`<details class="group-initiative">` and using `details.group-initiative` for your custom CSS

**Comment by vtt-lair** [comment]
Thanks for pointing this out. That is a rather stupid mistake. Will work on it during this week.

**Comment by Aeristoka** [comment]
> Thanks for pointing this out. That is a rather stupid mistake. Will work on it during this week.

I'm nothing if not able to stumble upon weird crap 😄

**Comment by vtt-lair** [comment]
I've created a new task to refactor the headers: #29
