### ISSUE TITLE
Skip grouped combattants not working

### ISSUE THREAD

**Issue by snakch** [vtt-lair/foundry-group-initiative#37]
If I understand correctly, the intent of this option is that when going through the turn tracker, one wouldn't need to skip through all tokens belonging to a group, only the first one. Is this correct? If so that isn't working for me.

**Comment by vtt-lair** [comment]
Sorry I have been so quiet, I moved to a different country at the end of February and it's been a hectic past 5 months. Hope to get to issues loaded in the next few weeks.

**Comment by vtt-lair** [comment]
This was because the skipped grouped combat was initially added to the actual "grouping" code, that group everything under a collapsable expander (the experimental code). This however was so buggy, that I changed it to a setting that wasn't defaulted anymore and added the text to explain it's not working.

I've split this out however so that it isn't just linked to that experimental code, should work in the next release.
